repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -  id: check-yaml
    -  id: end-of-file-fixer
    -  id: trailing-whitespace
    -  id: check-case-conflict
    -  id: check-merge-conflict
    -  id: check-toml
    -  id: mixed-line-ending
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8/
    rev: 3.8.3
    hooks:
    - id: flake8
      additional_dependencies:
      - flake8-bandit
      - flake8-annotations
      - flake8-bugbear
      - flake8-builtins
      - flake8-comprehensions
      - flake8-cognitive-complexity
      - flake8-docstrings
      - flake8-eradicate
      - flake8-import-order
      - flake8-mutable
      - flake8-print
      - pep8-naming
