[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "declared_env"
author = "Andrey Solomatin"
author-email = "cjkjvfnby@gmail.com"
home-page = "https://github.com/Cjkjvfnby/declared_env"

requires-python = ">=3.9"


[tool.pytest.ini_options]
addopts = [
    "--doctest-modules",
    "--doctest-continue-on-failure",
    "--showlocals",
]


[tool.ruff]
lint.select = ["ALL"]
lint.ignore = [
    "ANN101", "ANN204", "ANN401",
    "D104", # no docstring in public package
    "D200", # One-line docstring should fit on one line with quotes
    "D212",  # Start first line of docstring on the line with quotes
    "RSE102",  # Remove parenthesis after raise Exception
    "D203",
    "FLY002", # fix produces invalid code https://github.com/astral-sh/ruff/issues/5150
    "G004", # logging with f string is ok
    "COM812",
    "ISC001",
    "D107", "D105", # docstring for magic method
]
line-length = 98
target-version = "py39"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"test/*" = ["D10", "D101", "D103", "S101", "ANN", "PLR2004"]
"./declared_env/_exceptions.py" = ["D107"]
"declared_env/_declared_variables.py" = ["FBT001", "FBT002"]

[tool.ruff.lint.mccabe]
max-complexity = 5

[tool.coverage.report]
exclude_also = [
    "if TYPE_CHECKING:",
    ]

[tool.ruff.format]
line-ending = "native"

[tool.mypy]
check_untyped_defs = true
exclude = [
'^test.*'
]
