name: Test and lint

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    paths:
      - '**.py'
      - '.github/workflows/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Black check
        run: |
          black . --check
      - name: Add annotation collector for flake8
        uses: rbialon/flake8-annotations@v1
      - name: Lint with flake8
        run: |
          flake8 . --count
      - name: Test with pytest
        run: |
          pytest --cov=declared_env
