name: Test and lint

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    paths:
      - '**.py'
      - '.github/workflows/**'
      - '.flake8'
      - 'requirements-dev.txt'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - uses: pre-commit/action@v3.0.0
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Test with pytest
        run: |
          pytest -v --cov=declared_env --cov-report xml:coverage.xml
      - name: Report coverage
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage.xml
          skip_covered: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 0
          show_missing: true
          link_missing_lines: true
          report_name: Project coverage
          link_missing_lines_source_dir: declared_env
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
