name: Lint

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.pip
      - name: Black chack
        run: |
          black . --check
      - name: Lint with flake8
        run: |
          flake8 . --count
