name: Merge master to weekly release
on:
  pull_request:
    branches: [ 'master' ]
    types: ['opened', 'reopened', 'synchronize']
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    environment: experimental
    steps:
      - uses: actions/checkout@v3
      - name: Merge master -> weekly release
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: weekly
          github_token: ${{ secrets.GITHUB_TOKEN }}
